# Site Settings
name: "Hossein Anvari"
title: "Hossein Anvari"
description: "Blogs of ideas and challenges; Capture-The-Flag, code and etc. "
meta_description: "Blogging about Capture-The-Flag(CTF) challenges, programming and intriguing subjects."
author: "Hossein Anvari"
author_description: "Blogging about Capture-The-Flag(CTF) challenges, programming and intriguing subjects."
# Details for the RSS feed generator
url:  'https://khz-intl.github.io/'
baseurl: ""
domain_name: 'https://khz-intl.github.io'

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

logo: true
paginate: 15
plugins: [jekyll-paginate, jekyll-sitemap]

google_analytics: 'UA-116486746-1'
disqus_shortname: 'Hossein-Anvari'


