# Site Settings
name: Hossein Anvari
description: Blogs of ideas and challenges
meta_description: "Blogging about Capture-The-Flag(CTF) challenges, programming and intriguing subjects."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://khz-intl.github.io'
google_analytics: 'UA-116486746-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://khz-intl.github.io/'
author: 'Hossein Anvari'
