name: Hossein Anvari
description: Blogs of ideas and challenges
meta_description: "Cracking/RE licensing protection and abit of capture the flag/"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://github.com/khz-intl/khz-intl.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate, github-pages]

# Details for the RSS feed generator
url:            'blog url'
author:         'Hossein Anvari'
