name: Hossein Anvari
description: Blogs of ideas and challenges
meta_description: "Blogging about cracking licensing protection/crack-me challenges and abit of capture the flag"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://github.com/khz-intl/khz-intl.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate, jekyll-sitemap]

# Details for the RSS feed generator
url:            'blog url'
author:         'Hossein Anvari'
